# Travis-CI file for pyDatView
language: python

python:
  - "2.7"
  - "3.6"
  - "3.7"
  - "3.8"
os:
  - linux
sudo: true

install:
  #  - sudo apt-get install python-wxgtk3.0
  - sudo apt-get install nsis
  - pip install -r _tools/travis_requirements.txt
  - pip install -r weio/requirements.txt

script:
  - make test
  - if [[ "$TRAVIS_TAG" == "" ]]; then export TRAVIS_TAG="vdev" ; fi

before_deploy:
  - git fetch --unshallow
  - export VERSION_NAME=`git describe | sed 's/\(.*\)-.*/\1/'`
  - export FULL_VERSION_NAME="version $VERSION_NAME"
  - if [[ "$TRAVIS_TAG" == "vdev" ]]; then export VERSION_NAME=$VERSION_NAME"-dev" ; fi
  - if [[ "$TRAVIS_TAG" == "vdev" ]]; then export FULL_VERSION_NAME="latest dev. version $VERSION_NAME" ; fi
  - echo $VERSION_NAME
  - pip install pynsist
  - pip install distlib
  - git clone https://github.com/takluyver/pynsist
  - mv pynsist/nsist nsist
  - make installer
  - mv build/nsis/pyDatView.exe "pyDatView_"$VERSION_NAME"_setup.exe"
  - mv _tools/pyDatView.cmd build/nsis/
  - mv _tools/pyDatView.exe build/nsis/
  - mv build/nsis build/pyDatView_$VERSION_NAME
  - cd build && zip -r "../pyDatView_"$VERSION_NAME"_portable.zip" pyDatView_$VERSION_NAME
  - cd ..
  - ls

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  overwrite: true
  skip_cleanup: true
  file:
    - pyDatView*.exe
    - pyDatView*.zip
  name: $FULL_VERSION_NAME
  target_commitish: $TRAVIS_COMMIT
  tag_name: $TRAVIS_TAG
  on:
    tags: true
    branch: master
    condition: $TRAVIS_PYTHON_VERSION = 3.6
